TEMPLATE = subdirs

SUBDIRS += \
    acebsfwidget \
    acebsfwidget_signals \
    agastwidget \
    agastwidget_signals \   
    akazewidget\
    akazewidget_signals \
    briefwidget \
    briefwidget_signals \   
    briskwidget \
    briskwidget_signals \    
    clahewidget \
    clahewidget_signals \
    cmbfhewidget \
    cmbfhewidget_signals \
    daisywidget \
    daisywidget_signals \
    descriptormatcherwidget \
    descriptormatcherwidget_signals \  
    dhewidget \
    dhewidget_signals \
    fahewidget \
    fahewidget_signals \ 
    fastwidget \
    fastwidget_signals \    
    freakwidget \
    freakwidget_signals \   
    gfttwidget \
    gfttwidget_signals \   
    hmclahewidget \
    hmclahewidget_signals \
    hogwidget \
    hogwidget_signals \   
    kazewidget \
    kazewidget_signals \  
    latchwidget \
    latchwidget_signals \   
    lcebsescswidget \
    lcebsescswidget_signals \
    lucidwidget \
    lucidwidget_signals \ 
    msdwidget \
    msdwidget_signals \    
    mserwidget \
    mserwidget_signals \    
    msrcpwidget \
    msrcpwidget_signals \    
    noshpwidget \
    noshpwidget_signals \    
    orbwidget \
    orbwidget_signals \
    pohewidget \
    pohewidget_signals \    
    siftwidget \
    siftwidget_signals \
    starwidget \
    starwidget_signals \
    surfwidget \
    surfwidget_signals \
    walliswidget \
    walliswidget_signals \
    rswhewidget \
    rswhewidget_signals \
    thumbnailswidget
